### ISSUE TITLE
Updated City Website

### ISSUE THREAD

**Issue by alex-stout** [clearwater-labs/parkingNotifier#15]
**Describe the bug**
The city website must have stopped doing the banner on the top. 

**Screenshots**
<img width="1920" alt="screen shot 2018-12-03 at 9 37 26 am" src="https://user-images.githubusercontent.com/17804548/49383819-3f017480-f6df-11e8-94f9-471eca0d0660.png">

**Comment by alex-stout** [comment]
Just checked again and it's up:
![screen shot 2018-12-03 at 10 14 04 pm](https://user-images.githubusercontent.com/17804548/49418629-d353f180-f748-11e8-8cd4-5b1b3fce5e7d.png)

@TMisch from what I can tell the "Latest News" section is probably going to be more reliable... what do you think?

**Comment by TMisch** [comment]
I'd agree with that. Seeing as you were ticketed before the announcement arrived via the banner. I'll just plan on finding a way to scrape the "Latest News" for something related to the Alternate Side Parking

**Comment by TMisch** [comment]
I'm hoping to get it set up for scraping today so hopefully I'll get it before it goes away

**Comment by TMisch** [comment]
Should be fixed with #25
