### ISSUE TITLE
Navbar showing incorrectly on register page

### ISSUE THREAD

**Issue by StevenJNelson** [clearwater-labs/parkingNotifier#21]
**Describe the bug**
The navbar is cutting off the very top of the register page.

**To Reproduce**
1. Go to the development server
2. Click on 'register'
3. See top of page

**Expected behavior**
Expect to see the navbar not cutting off any of the page body.

**Comment by alex-stout** [comment]
Hey Steven, 

I noticed the bug too. I have a fix. I'll link the pull request when I make it.

**Comment by alex-stout** [comment]
Should be fixed in #22

**Comment by alex-stout** [comment]
<img width="1132" alt="screen shot 2018-12-06 at 11 52 04 pm" src="https://user-images.githubusercontent.com/17804548/49630046-1bc21800-f9b2-11e8-8cb6-4785f261e1c2.png">

Live site after #22 merge.
