### ISSUE TITLE
Running Cron Job Restarts Server

### ISSUE THREAD

**Issue by alex-stout** [clearwater-labs/parkingNotifier#43]
**Describe the bug**
After looking at the server logs, it looks like the server may be restarting after the cron job runs to scrape the city website. This probably shouldn't happen just in case there's an open connection on the API.

**To Reproduce**
1. Have API running
2. Make the cron job fire to scrape the city website
3. Read logs to see if the API restarted

**Screenshots**
![screen shot 2018-12-16 at 6 02 38 pm](https://user-images.githubusercontent.com/17804548/50061787-ce3f6b00-0168-11e9-8557-64281d3266f6.png)

**Comment by TMisch** [comment]
![image](https://user-images.githubusercontent.com/29696546/50062636-c8985400-016d-11e9-9e67-31e9c0256df6.png)

Not able to replicate the test on my machine right now, will have to look at it with @alex-stout next time we're in the office to see if we can re-create it.

**Comment by alex-stout** [comment]
You're right. My mistake.
