### ISSUE TITLE
Require HTTPS

### ISSUE THREAD

**Issue by siasmj** [clearwater-labs/parkingNotifier#56]
This project looks great so far! I just have one suggestion. When I went to register, Chrome warned me that the registration form was not secure. Would it be possible to require HTTPS so people don't get this warning? You should be able to get a free certificate to cover the domain from Let's Encrypt (https://letsencrypt.org/getting-started/) or another source. The form doesn't ask for any particularly sensitive information, but some people may be dissuaded from using this service if they see a security warning especially as the major browsers continue to push forward with their "HTTPS everywhere" initiative.

**Comment by alex-stout** [comment]
Thanks for letting us know! I'm currently working on this issue. We have a https://www.parkingnotifier.com site and it looks like the cache hasn't updated yet. Usually it's a 24 hr cycle with the cache refresh. Our release #33 was cut 22 hrs ago so I'm going to keep monitoring the site over the next few hours to make sure the transition happens and without breaking anything.

**Comment by alex-stout** [comment]
This problem is fixed now. There was a slew of problems that have been fixed that were causing a certificate to be flagged as malicious. @siasmj thanks for bringing this to our attention!
